//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPrortfolyo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSkill
    {
        public int Skillıd { get; set; }
        public string SkillTittle { get; set; }
        public Nullable<byte> SkillValue { get; set; }
    }
}
